version: '3.9'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../../:/var/www/symfony
    depends_on:
      - php

  php:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.php
    volumes:
      - ../../:/var/www/symfony
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    platform: linux/arm64/v8
    volumes:
      - mysql_data:/var/lib/mysql
    env_file: 
      - ../../.env 
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
