api_platform:
  title: Symfony Pokemon API
  version: 0.2.0
  formats:
    jsonld: ["application/ld+json"]
  swagger:
    api_keys:
      access_token:
        name: Authorization
        type: header
  # docs_formats:
  #   jsonld: ["application/ld+json"]
  #   jsonopenapi: ["application/vnd.openapi+json"]
  #   html: ["text/html"]
  # defaults:
  #   stateless: true
  #   cache_headers:
  #     vary: ["Content-Type", "Authorization", "Origin"]
  #   extra_properties:
  #     standard_put: true
  #     rfc_7807_compliant_errors: true
  # event_listeners_backward_compatibility_layer: false
  # keep_legacy_inflector: false
