version: '3.8'

services:
  fpm:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile.fpm
    restart: always
    volumes:
      - symfony_app:/app

  nginx:
    image: nginx:alpine
    ports:
      - '${SERVER_IP}:80:80'
      - '${SERVER_IP}:443:443'
    volumes:
      - /var/www/api.pokedexia.com/docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/api.pokedexia.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/api.pokedexia.com/privkey.pem:/etc/ssl/private/privkey.pem:ro
      - symfony_app:/app:ro
    depends_on:
      - fpm
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${SERVER_IP}:3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
    ports:
      - "${SERVER_IP}:8080:80"
    depends_on:
      - mysql

volumes:
  db_data:
  symfony_app:
